stages:
  - install
  - test
  - deploy_prod

.artifacts: &artifacts
  artifacts:
    paths:
      - .venv/

image: paradoxxxzero/python-node-yarn-postgresql:latest

install:
  stage: install
  script:
    - make install
  <<: *artifacts

lint:
  stage: test
  script:
    - make lint
  dependencies:
    - install

.image: &image_deploy_jobs
  image: grewn0uille/deploy-tools:latest

deploy_prod:
  stage: deploy_prod
  <<: *image_deploy_jobs
  script:
    - make deploy-prod
  dependencies: []
  only:
    - master
